services:
  - type: web
    name: turismo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
